### ISSUE TITLE
Where is ShowProgress class

### ISSUE THREAD

**Issue by daejoongkim-aisoft** [farihachaiti/DoKaraokeAI#2]
Can I ask where the " ShowProgress" class is(what package to import) ? it is used in ExtractAudio, etc.

**Comment by farihachaiti** [comment]
This shouldnt be a problem. This class just forms a progressbar which is not needed. However, I have added the class file please do another pull. If it throws error then just ommit the ShowProgress file and comment out the progressdialog codes. This does not affect the main thread.

**Comment by daejoongkim-aisoft** [comment]
thanks a lot for your reply !

2024년 4월 9일 (화) 오후 9:26, farihachaiti ***@***.***>님이 작성:
